traefik:
  deployment:
    kind: DaemonSet

  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

  additionalArguments:
    # Temporary, untill we get cert-manager or something working
    # to allow Traefik to reverse-provy against https services that
    # have self-signed certs
    - --serverstransport.insecureskipverify=true

  service:
    spec:
      loadBalancerIP: 192.168.33.1
