traefik:
  deployment:
    kind: DaemonSet

  service:
    spec:
      type: NodePort

  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

  additionalArguments:
    # Temporary, untill we get cert-manager or something working
    # to allow Traefik to reverse-provy against https services that
    # have self-signed certs
    - --serverstransport.insecureskipverify=true
    # Trust forwarded headers to not mess up cookies, Host header, etc
    - --entryPoints.web.forwardedHeaders.insecure=true
    - --entryPoints.websecure.forwardedHeaders.insecure=true
